---
# Default values for local Traefik deployment via Helm
traefik_namespace: traefik
traefik_release_name: traefik
traefik_chart_repo_name: traefik
traefik_chart_repo_url: https://helm.traefik.io/traefik
traefik_chart_name: traefik
traefik_chart_version: "25.0.0"
traefik_kubeconfig: /etc/kubernetes/admin.conf
traefik_service_type: NodePort
traefik_web_node_port: 32080
traefik_websecure_node_port: 32443
