defaultSettings:
  defaultDataPath: "/srv/longhorn"
  nodeSelector:
    {{ longhorn_node_selector_key | default('longhorn.io/enable') }}: "{{ longhorn_node_selector_value | default('true') }}"
preUpgradeChecker:
  jobEnabled: false
service:
  ui:
    type: "ClusterIP"
ingress:
  enabled: true
  ingressClassName: "traefik"
  host: "longhorn.local"
  paths:
    - path: "/"
      pathType: "Prefix"
  tls: []

longhornManager:
  nodeSelector:
    {{ longhorn_node_selector_key | default('longhorn.io/enable') }}: "{{ longhorn_node_selector_value | default('true') }}"

longhornDriver:
  nodeSelector:
    {{ longhorn_node_selector_key | default('longhorn.io/enable') }}: "{{ longhorn_node_selector_value | default('true') }}"
